(time (let ((prime 600851475143))
        (declare (integer prime)
                 (optimize (speed 3) (safety 0) (debug 0) (compilation-speed 3)))
        (loop for i of-type fixnum = 2 then (1+ i)
              while (< i prime)
              if (= (mod prime i) 0)
                do (setf prime (/ prime i)
                         i (1- i))
              finally (print i))))
(quit)
